version: 2

project_name: wifi-provisioner

before:
  hooks:
    - go mod tidy

builds:
  - id: wifi-provisioner
    main: ./main.go
    binary: wifi-provisioner
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
    flags:
      - -trimpath

archives:
  - id: release-archives
    formats: [ tar.gz ]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE*  # include license if present

checksum:
  name_template: 'checksums.txt'

nfpms:
  - id: deb
    package_name: wifi-provisioner
    vendor: Fyve Labs
    homepage: https://github.com/Fyve-Labs/wifi-provisioner
    maintainer: Fyve Labs <viet@fyve.dev>
    license: MIT
    description: "BLE-based Wi‑Fi provisioner that configures NetworkManager via nmcli."
    formats: [ deb ]
    ids:
      - wifi-provisioner
    bindir: /usr/local/bin
    file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
    recommends:
      - network-manager
      - bluez
    contents:
      - src: packaging/scripts/check-connectivity-and-provision.sh
        dst: /usr/local/bin/check-connectivity-and-provision.sh
        file_info:
          mode: 0755
      - src: packaging/systemd/wifi-provisioner-autostart.service
        dst: /lib/systemd/system/wifi-provisioner-autostart.service
        file_info:
          mode: 0644
    scripts:
      postinstall: packaging/scripts/postinstall.sh
      postremove: packaging/scripts/postremove.sh

changelog:
  use: git

release:
  # Rely on the tag pushed (vX.Y.Z) to create the GitHub release
  draft: false
  prerelease: auto
